### ISSUE TITLE
How to get the CLIC datasets?

### ISSUE THREAD

**Issue by Cassieyy** [JiangWeibeta/IQA-TMFM#1]
Great job on your work! I was wondering if you could help me obtain the 2022 CLIC datasets mentioned in your paper, as I couldn't locate them on the homepage (http://compression.cc/). Thank you in advance for your assistance.

**Comment by JiangWeibeta** [comment]
You can get the dataset from http://compression.cc/tasks/.
See Perceptual metrics part.

**Comment by Cassieyy** [comment]
您的邮件已收到哦我会及时处理哒~

**Comment by Cassieyy** [comment]
> You can get the dataset from http://compression.cc/tasks/. See Perceptual metrics part.

Thank you for your response. However, I noticed that the dataset you provided (https://storage.googleapis.com/clic2021_public/perceptual/clic_2021_perceptual_valid.zip) is labeled as the validation set and consists of 2733 images. I would like to confirm whether this is the dataset used in your paper.

**Comment by JiangWeibeta** [comment]
Yes
